export const APPWRITE_PROJECT_ID = process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID;
export const APPWRITE_API_ENDPOINT =
  process.env.EXPO_PUBLIC_APPWRITE_API_ENDPOINT;
export const APPWRITE_PLATFORM_NAME =
  process.env.EXPO_PUBLIC_APPWRITE_PLATFORM_NAME;

export const APPWRITE_DATABASE_ID =
  process.env.EXPO_PUBLIC_APPWRITE_DATABASE_ID;
export const APPWRITE_TAG_COLLECTION_ID =
  process.env.EXPO_PUBLIC_APPWRITE_TAG_COLLECTION_ID;
export const APPWRITE_SUB_TASK_COLLECTION_ID =
  process.env.EXPO_PUBLIC_APPWRITE_SUB_TASK_COLLECTION_ID;
export const APPWRITE_TASK_DATABASE_ID =
  process.env.EXPO_PUBLIC_APPWRITE_TASK_DATABASE_ID;
