export const APPWRITE_PROJECT_ID = process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID;
export const APPWRITE_API_ENDPOINT =
  process.env.EXPO_PUBLIC_APPWRITE_API_ENDPOINT;
export const APPWRITE_PLATFORM_NAME =
  process.env.EXPO_PUBLIC_APPWRITE_PLATFORM_NAME;
